pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Abhi-chintu/Sonarqube.git']])
		sh 'cd Sonarqube'
                echo 'Git Checkout Completed'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('ServerNameSonar') {
                    bat '''mvn clean verify sonar:sonar -Dsonar.projectKey=springboot -Dsonar.projectName='springboot' -Dsonar.host.url=http://65.2.179.112:9000 -Dsonar.login=sqa_fb6f33f8a9de25518de4da1706cf54a932be8370''' //port 9000 is default for sonar
                    echo 'SonarQube Analysis Completed'
                }
            }
        }
    }
}
